---
title: "In-Class Announcements"
author: "Foundations of Business Analytics"
institute: "Semester 1 2026"
format: 
  beamer: 
    aspectratio: 32
    navigation: horizontal
    theme: mousteau
---

# Week 5

## Mid Semester Test: Content

- **Format**: **\alert{20 questions}**, mixed **\alert{MCQ and short answer}** format 
- **Topic Coverage**: Everything from the **\alert{first 5 weeks lectures}** (including lecture readings)
  - With a strong focus on **R code** ...
  - ... Because the code we have covered so far forms the base of everything we do in the remaining weeks of the semester
  
## Mid Semester Test: Lockdown Browser

- To complete the MST, **you must use the Respondus LockDown browser**. 

- Further information, including installation instructions are available at the link below:

[LockDown Browser](https://students.unimelb.edu.au/course-admin/exams/device-preparation-on-campus-exams#LMS-Quiz)

- **Install and test** the browser works for you **before the MST**
  - Really, do it this week!

- We cannot guarantee we can help with browser on the day of the MST!


# Week 2 

## Mid Semester Test

Format:

- **When**: Tuesday, the **\alert{14th April}**, between **\alert{15:00 and 18:00 AEST}**
- **Where**: On **\alert{Canvas}**
- **How long**: You have **\alert{30 mins once started}**, one attempt
- **Format**: **\alert{20 questions}**, mixed **\alert{MCQ and short answer}** format 
- **Topic Coverage**: Everything from the **\alert{first 5 weeks lectures}**

Notes:

- Lectures still take place in Week 6, Mid Semester Test is additional time you must spend on the course
- If you have **\alert{classes over the entire 3 hour window}**, email **accounting-teaching@unimelb.edu.au** AND CC **cmce-10002@unimelb.edu.au**
    - Report your name and student ID
    - Explain the clash.
    - **Do it soon!!**
